from flask import Flask, request
import json

app = Flask(__name__)

# Enables taking into account CO2 emission allowances 
co2_active = True

# Request entrypoint and main program
# 1. Reads the data and creates a list of the powerplants with each parameters.
# 2. Calculates the cost-per-power-unit of each powerplant
# 3. Sorts the plants using a quickshort algorithm to acomplish merit-order
# 4. Distributes the load between the plants
# 5. Formats the data and sends it back as the body of the request.
@app.post('/productionplan')
def production_plan_post():
    request_data = request.get_json()
    plants_consumption = []
    for plant in request_data["powerplants"]:
        plants_consumption.append(calc_plant_consumption(plant,request_data["fuels"]))
    quickshort_plants(plants_consumption,0,len(plants_consumption)-1)
    get_load(plants_consumption,request_data["load"])
    
    return json.dumps(transform_answer(plants_consumption))

# Formats the power plants info into the desired answer format
# {
#    "name": plant's name
#    "p": power load generated by the plant
# }
def transform_answer(plants: list) -> list:
    answer = []
    for plant in plants:
        answer.append({
            "name": plant["name"],
            "p": round(plant["p"],1) 
        })
    return answer 

# Distribute the load between the given plants taking into account each plant maximun and minimum power load
def get_load(plants: list, load: int):
    for i in range(len(plants)):
        plant = plants[i]
        if plant["pmin"] < load:
            if plant["pow"] <= load:
                plant["p"] = plant["pow"]
                load -= plant["p"]
            else:
                plant["p"] = load
                load = 0
                break
        else:
            last_plant = plants[i-1]
            defficit = plant["pmin"] - load
            if last_plant["p"] - defficit >= last_plant["pmin"]:
                last_plant["p"] -= defficit
                plant["p"] = plant["pmin"]
                load = 0
                break

# Quickshort algorithm used to order the plants by the merit-order
def quickshort_plants(plants: list, low: int, high: int):
    if low < high:
        piv_pointer = part_short(plants, low, high)
        quickshort_plants(plants, low, piv_pointer - 1)
        quickshort_plants(plants, piv_pointer + 1, high)
    
def part_short(plants: list, low: int, high: int) -> int:
    i = low -1
    for j in range(low, high):
        
        if plants[j]["unit_cost"] == plants[high]["unit_cost"]:
            if plants[j]["pow"] > plants[high]["pow"]:
                i += 1
                (plants[i], plants[j]) = (plants[j], plants[i])
        elif plants[j]["unit_cost"] <= plants[high]["unit_cost"]:
            i += 1
            (plants[i], plants[j]) = (plants[j], plants[i])
    (plants[high],plants[i+1]) = (plants[i+1],plants[high])
    return i + 1

# Calculates the cost per unit of each power plant and in case the plant is of 
# type windturbine calculates the power generated by the wind
def calc_plant_consumption(plant: dict, fuels: dict, pow: int = -1) -> dict:
    if pow == -1: pow = plant["pmax"]
    res_values = {
        "cost": 0,
        "pow": pow,
        "name": plant["name"],
        "unit_cost" : 0,
        "pmin": plant["pmin"],
        "p": 0
    }
    match plant["type"]:
        case "gasfired":
            if co2_active: co2_tons_allowance = pow * .3 * fuels["co2(euro/ton)"]
            else: co2_tons_allowance = 0
            gas_cost = pow * fuels["gas(euro/MWh)"] / plant["efficiency"]
            res_values["cost"] = co2_tons_allowance + gas_cost
            res_values["unit_cost"] = res_values["cost"] / res_values["pow"]
        case "turbojet":
            res_values["cost"] = pow * fuels["kerosine(euro/MWh)"] / plant["efficiency"]
            res_values["unit_cost"] = res_values["cost"] / res_values["pow"]
        case "windturbine":
            res_values["pow"] = plant["pmax"] * fuels["wind(%)"] / 100
    return res_values

if __name__ == '__main__':
    app.run(port=8888)